config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :description, presence: true
  validates :price_per_night, numericality: true, presence: true
  validates :number_of_guests, numericality: { only_integer: true }, presence: true
  validates :picture, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show]

  def index
    @flats = Flat.all.reverse
  end

  def show
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flats_path
    else
      render :new
    end
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests, :picture)
  end

  def set_flat
    @flat = Flat.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<div class="container">
  <div class="page-title">
    <h1>List of flats</h1>
  </div>

  <% @flats.each do |flat|  %>
    <div class="flat-card-index">
      <div class="flat-image-index">
        <img src=<%= flat.picture %> alt="">
      </div>
      <div class="flat-summary-index">
        <h3><%= link_to flat.name, flat_path(flat), {class: "flat-summary-link"} %></h3>
        <p><%= flat.address %></p>
        <div class="flat-summary-price-guest">
          <p><i class="fas fa-user-friends"></i>  <%= flat.number_of_guests %></p>
          <p><i class="fas fa-pound-sign"></i>  <%= flat.price_per_night %> per night</p>
        </div>
      </div>
    </div>

  <% end %>
</div>

app/views/flats/new.html.erb
<div class="container">
  <div class="page-title">
    <h1>New Flat</h1>
  </div>

  <%= form_for(@flat) do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :address %>
      <%= f.text_field :address, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_field :description, class: 'form-control' %>
    </div>

     <div class="form-group">
      <%= f.label :price_per_night %>
      <%= f.text_field :price_per_night, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :number_of_guests %>
      <%= f.text_field :number_of_guests, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :picture %>
      <%= f.text_field :picture, class: 'form-control' %>
    </div>

    <%= f.submit class: 'btn btn-dark' %>
  <% end %>
</div>

app/views/flats/show.html.erb
<div class="banner-img">
  <img src=<%= @flat.picture %> alt="">
</div>

<div class="container detail-area">
  <div class="detail-box page-title">
    <h2><%= @flat.name %></h1>
    <p><%= @flat.address %></p>
  </div>

  <div class="detail-box description">
    <h3>A little bit more about this flat:</h3>
    <p><%= @flat.description %></p>
  </div>

  <div class="detail-box details">
    <h3>Details:</h3>
    <div class="flat-summary-price-guest">
      <p><i class="fas fa-user-friends"></i>  <%= @flat.number_of_guests %></p>
      <p><i class="fas fa-pound-sign"></i>  <%= @flat.price_per_night %> per night</p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/shared/_footer.html.erb
<div class="container">
  <div class="footer">
    <p>Made at Le Wagon with <i class="fas fa-heart"></i> and <i class="fas fa-rocket"></i></p>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-lewagon">
  <p>Simple Airbnb</p>
  <p><%= link_to "+ New Flat", new_flat_path  %></p>
</div>